# Generated by Django 2.0.4 on 2018-04-22 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalPoint',
            fields=[
                ('opp_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('opp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('opp_uniqueid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('opp_lon', models.FloatField(blank=True, null=True)),
                ('opp_lat', models.FloatField(blank=True, null=True)),
                ('opp_geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('opp_taftapcode', models.DateField(blank=True, null=True)),
                ('opp_date_start', models.DateField(blank=True, null=True)),
                ('opp_date_end', models.CharField(blank=True, max_length=255, null=True)),
                ('opp_track_nb', models.IntegerField(blank=True, null=True)),
                ('opp_tunnel_nb', models.IntegerField(blank=True, null=True)),
                ('opp_platform_nb', models.IntegerField(blank=True, null=True)),
                ('oty_id', models.IntegerField(blank=True, null=True)),
                ('mem_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'operational_point',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SectionOfLine',
            fields=[
                ('sol_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sol_length', models.FloatField(blank=True, null=True)),
                ('sol_nature', models.CharField(blank=True, max_length=255, null=True)),
                ('sol_imcode', models.CharField(blank=True, max_length=255, null=True)),
                ('sol_date_start', models.DateField(blank=True, null=True)),
                ('sol_date_end', models.DateField(blank=True, null=True)),
                ('sol_track_nb', models.IntegerField(blank=True, null=True)),
                ('sol_tunnel_nb', models.IntegerField(blank=True, null=True)),
                ('mem_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('opp_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opp_end', to='geo_app.OperationalPoint')),
                ('opp_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opp_start', to='geo_app.OperationalPoint')),
            ],
            options={
                'db_table': 'section_of_line',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sectionofline',
            unique_together={('opp_start', 'opp_end')},
        ),
    ]
