# Generated by Django 2.0.4 on 2018-04-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalpoint',
            options={'managed': False},
        ),
    ]
