# Generated by Django 2.0.2 on 2018-04-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operationalpoint',
            old_name='mem_id',
            new_name='mem',
        ),
        migrations.RenameField(
            model_name='operationalpoint',
            old_name='oty_id',
            new_name='oty',
        ),
        migrations.AddField(
            model_name='operationalpoint',
            name='doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Document'),
        ),
    ]
