# Generated by Django 2.0.2 on 2018-04-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_auto_20180429_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionofline',
            name='opp_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_end', to='geo_app.OperationalPoint', to_field='opp_uniqueid'),
        ),
        migrations.AlterField(
            model_name='sectionofline',
            name='opp_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_start', to='geo_app.OperationalPoint', to_field='opp_uniqueid'),
        ),
    ]
