# Generated by Django 2.0.4 on 2018-04-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0002_auto_20180422_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalpoint',
            options={'managed': True},
        ),
    ]
