# Generated by Django 2.0.4 on 2018-04-22 14:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0003_auto_20180422_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalpoint',
            name='opp_geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857),
        ),
    ]
