# Generated by Django 2.0.4 on 2018-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0004_auto_20180422_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalpoint',
            name='opp_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationalpoint',
            name='opp_taftapcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
