# Generated by Django 2.0.4 on 2018-04-24 10:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0006_auto_20180423_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalpoint',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
