# Generated by Django 2.0.4 on 2018-04-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0007_auto_20180424_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='sectionofline',
            name='opp_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_end', to='geo_app.OperationalPoint'),
        ),
        migrations.AlterField(
            model_name='sectionofline',
            name='opp_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_start', to='geo_app.OperationalPoint'),
        ),
        migrations.AddField(
            model_name='operationalpoint',
            name='doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Document'),
        ),
    ]
