# Generated by Django 2.0.4 on 2018-04-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0008_auto_20180425_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('lin_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lin_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mem_version', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Document')),
            ],
            options={
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpType',
            fields=[
                ('oty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('oty_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'op_type',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='operationalpoint',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='sectionofline',
            name='lin_id',
        ),
        migrations.RemoveField(
            model_name='sectionofline',
            name='mem_id',
        ),
        migrations.AlterField(
            model_name='operationalpoint',
            name='mem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Member'),
        ),
        migrations.AlterField(
            model_name='operationalpoint',
            name='oty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.OpType'),
        ),
        migrations.AddField(
            model_name='line',
            name='mem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Member'),
        ),
        migrations.AddField(
            model_name='sectionofline',
            name='lin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Line'),
        ),
        migrations.AddField(
            model_name='sectionofline',
            name='mem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Member'),
        ),
    ]
