# Generated by Django 2.0.4 on 2018-04-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0009_auto_20180425_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppParameterValue',
            fields=[
                ('opv_id', models.AutoField(primary_key=True, serialize=False)),
                ('opv_value', models.CharField(blank=True, max_length=255, null=True)),
                ('opp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.OperationalPoint')),
            ],
            options={
                'db_table': 'opp_parameter_value',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('par_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('par_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('par_type', models.CharField(choices=[(1, 'TRACK'), (2, 'SOL_TRACK'), (3, 'TUNNEL'), (4, 'PLATFORM')], max_length=254)),
            ],
            options={
                'db_table': 'parameter',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='oppparametervalue',
            name='par_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Parameter'),
        ),
        migrations.AlterUniqueTogether(
            name='oppparametervalue',
            unique_together={('opp_id', 'par_name', 'opv_value')},
        ),
    ]
