# Generated by Django 2.0.4 on 2018-04-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0010_auto_20180425_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterDefinition',
            fields=[
                ('ppv_id', models.AutoField(primary_key=True, serialize=False)),
                ('par_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('ppv_value', models.CharField(blank=True, max_length=255, null=True)),
                ('ppv_optional_value', models.CharField(blank=True, max_length=255, null=True)),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_app.Parameter')),
            ],
            options={
                'db_table': 'parameter_definition',
                'managed': True,
            },
        ),
    ]
