# Generated by Django 2.0.4 on 2018-04-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0011_parameterdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolParameterValue',
            fields=[
                ('spv_id', models.AutoField(primary_key=True, serialize=False)),
                ('spv_value', models.CharField(blank=True, max_length=255, null=True)),
                ('par_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.Parameter')),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_app.SectionOfLine')),
            ],
            options={
                'db_table': 'sol_parameter_value',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='solparametervalue',
            unique_together={('sol', 'par_name', 'spv_value')},
        ),
    ]
